const TODOS_FILTER_ALL = `TODOS_FILTER_ALL`;
const TODOS_FILTER_DONE = `TODOS_FILTER_DONE`;
const TODOS_FILTER_NOT_DONE = `TODOS_FILTER_NOT_DONE`;

export { TODOS_FILTER_ALL, TODOS_FILTER_DONE, TODOS_FILTER_NOT_DONE };
